# https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose-ru
version: "3"
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    hostname: certbot
    # restart: always
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - ./etc:/etc/letsencrypt
      - ./var:/var/lib/letsencrypt
      - ./log:/var/log/letsencrypt
      - /opt/docker-proxy/default/www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email webmaster@example.com --agree-tos --no-eff-email -d example.com -d www.example.com -d example.ru
